/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateAccountRequest,
  CreateExpenseRequest,
  CreateIncomeRequest,
  GetBalanceParams,
  GetEvolutionExpensesResponse,
  GetEvolutionIncomesResponse,
  GetExpenseByIdResponse,
  GetExpensesGetEvolutionExpensesParams,
  GetExpensesParams,
  GetExpensesResponse,
  GetIncomeByIdResponse,
  GetIncomesGetevolutionincomesParams,
  GetIncomesParams,
  GetIncomesResponse,
  GetUserProfileResponse,
  LoginRefreshTokenRequest,
  LoginRequest,
  LoginResponse,
  MonthBalanceResponse,
  SignUpRequest,
  SignUpResponse,
  UpdateExpenseRequest,
  UpdateIncomeRequest
} from './types'
import { customInstance } from '../services/custom-instance';



type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


  /**
 * @summary Creates a new user
 */
export const postAuthSignup = (
    signUpRequest: SignUpRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<SignUpResponse>(
      {url: `/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signUpRequest
    },
      options);
    }
  
/**
 * @summary Login to Finans
 */
export const postAuthLogin = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<LoginResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      options);
    }
  
/**
 * @summary Refresh token
 */
export const postAuthRefreshToken = (
    loginRefreshTokenRequest: LoginRefreshTokenRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<LoginResponse>(
      {url: `/auth/refreshToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRefreshTokenRequest
    },
      options);
    }
  
export const logout = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Creates a new account
 */
export const postAccounts = (
    createAccountRequest: CreateAccountRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccountRequest
    },
      options);
    }
  
/**
 * @summary Creates a new income
 */
export const postIncomes = (
    createIncomeRequest: CreateIncomeRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/incomes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createIncomeRequest
    },
      options);
    }
  
/**
 * @summary Get all incomes
 */
export const getIncomes = (
    params: GetIncomesParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetIncomesResponse[]>(
      {url: `/incomes`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Update income data
 */
export const putIncomes = (
    updateIncomeRequest: UpdateIncomeRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/incomes`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateIncomeRequest
    },
      options);
    }
  
/**
 * @summary Gets income by id
 */
export const getIncomesId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetIncomeByIdResponse>(
      {url: `/incomes/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Deletes the income
 */
export const deleteIncomesId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/incomes/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * @summary Get evolution incomes
 */
export const getIncomesGetevolutionincomes = (
    params: GetIncomesGetevolutionincomesParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetEvolutionIncomesResponse[]>(
      {url: `/incomes/getevolutionincomes`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Create an expense
 */
export const postExpenses = (
    createExpenseRequest: CreateExpenseRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/expenses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createExpenseRequest
    },
      options);
    }
  
/**
 * @summary Get expenses
 */
export const getExpenses = (
    params: GetExpensesParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetExpensesResponse[]>(
      {url: `/expenses`, method: 'GET',
        params
    },
      options);
    }
  
/**
 * @summary Updates expense
 */
export const putExpenses = (
    updateExpenseRequest: UpdateExpenseRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/expenses`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateExpenseRequest
    },
      options);
    }
  
/**
 * @summary Get expense by id
 */
export const getExpensesId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetExpenseByIdResponse>(
      {url: `/expenses/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Delete expense
 */
export const deleteExpensesId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/expenses/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * @summary Get evolution expenses
 */
export const getExpensesGetEvolutionExpenses = (
    params: GetExpensesGetEvolutionExpensesParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetEvolutionExpensesResponse[]>(
      {url: `/expenses/getEvolutionExpenses`, method: 'GET',
        params
    },
      options);
    }
  
export const userProfile = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetUserProfileResponse>(
      {url: `/user/profile`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Gets the month balance
 */
export const getBalance = (
    params: GetBalanceParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<MonthBalanceResponse>(
      {url: `/balance`, method: 'GET',
        params
    },
      options);
    }
  
export type PostAuthSignupResult = NonNullable<Awaited<ReturnType<typeof postAuthSignup>>>
export type PostAuthLoginResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
export type PostAuthRefreshTokenResult = NonNullable<Awaited<ReturnType<typeof postAuthRefreshToken>>>
export type LogoutResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type PostAccountsResult = NonNullable<Awaited<ReturnType<typeof postAccounts>>>
export type PostIncomesResult = NonNullable<Awaited<ReturnType<typeof postIncomes>>>
export type GetIncomesResult = NonNullable<Awaited<ReturnType<typeof getIncomes>>>
export type PutIncomesResult = NonNullable<Awaited<ReturnType<typeof putIncomes>>>
export type GetIncomesIdResult = NonNullable<Awaited<ReturnType<typeof getIncomesId>>>
export type DeleteIncomesIdResult = NonNullable<Awaited<ReturnType<typeof deleteIncomesId>>>
export type GetIncomesGetevolutionincomesResult = NonNullable<Awaited<ReturnType<typeof getIncomesGetevolutionincomes>>>
export type PostExpensesResult = NonNullable<Awaited<ReturnType<typeof postExpenses>>>
export type GetExpensesResult = NonNullable<Awaited<ReturnType<typeof getExpenses>>>
export type PutExpensesResult = NonNullable<Awaited<ReturnType<typeof putExpenses>>>
export type GetExpensesIdResult = NonNullable<Awaited<ReturnType<typeof getExpensesId>>>
export type DeleteExpensesIdResult = NonNullable<Awaited<ReturnType<typeof deleteExpensesId>>>
export type GetExpensesGetEvolutionExpensesResult = NonNullable<Awaited<ReturnType<typeof getExpensesGetEvolutionExpenses>>>
export type UserProfileResult = NonNullable<Awaited<ReturnType<typeof userProfile>>>
export type GetBalanceResult = NonNullable<Awaited<ReturnType<typeof getBalance>>>
