/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PlotResponse } from './plotResponse';

export interface ExpenseResponse {
  id: number;
  description: string;
  amount: number;
  fixed: boolean;
  date: string;
  plots: PlotResponse;
}
