/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetExpensesGetEvolutionExpensesParams = {
  AccountId: number;
  StartDate?: Date;
  EndDate?: Date;
};
