/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponse } from './userResponse';

export interface LoginResponse {
  userResponse: UserResponse;
  token: string;
  refreshToken: string;
}
