/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetIncomesResponse } from './getIncomesResponse';

export interface PagedListOfGetIncomesResponse {
  items: GetIncomesResponse[];
  page: number;
  pageSize: number;
  totalItems: number;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
}
