/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GetExpensesResponse } from './getExpensesResponse';

export interface PagedListOfGetExpensesResponse {
  items: GetExpensesResponse[];
  page: number;
  pageSize: number;
  totalItems: number;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
}
