/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */

export interface PlotResponse {
  id?: number;
  month?: number;
  year?: number;
  plotCount?: string;
}
