/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Finans | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AccountResponse } from './accountResponse';

export interface UserResponse {
  username: string;
  accounts: AccountResponse[];
}
